config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true
  validates :password, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    # @users = User.all
    # render "index"
    # render plain: "ok"
    # render html: helpers.tag.strong('Not Found')
    # render js: "alert('Hello Hardik');"
    # render body: "raw"
    # render file: "#{Rails.root}/public/404.html", layout: false
    # render status: 404
    # render status: :forbidden
    # render :abc
    
  end

  def edit
  end

end

# variant

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LayoutRenderimg</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<center>
<h2>Users Listing</h2>
<table> 
<th>Username</th>
<th>Password</th>
<th>Actions</th>
<% @users.each do |user| %>
<tr>
<td><%= user.username %></td>
<td><%= user.password %></td>
<td><%= button_to "show", user_path(user),method: :get %></td>
</tr>
<% end %>
</table>
<%= link_to "new", new_user_path,method: :get %>
</center>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%#= javascript_include_tag "main" %>
<%#= javascript_include_tag "main", "/sum/sum" %>
<%#= stylesheet_link_tag "main" %>
<%#= image_tag "1.png", {height: 400} %>
<%#= video_tag "video_1.mp4" %>
<%#= audio_tag "first.mp3" %>

app/views/users/show.html.erb
<center>
<table> 
<th>Username</th>
<th>Password</th>
<tr>
<td><%= @user.username %></td>
<td><%= @user.password %></td>
</tr>
</table>
</center>